version 4.3 - replacing GitHub for Wiki on main menu

diff --git a/appimagebuild/LinuxToys.AppDir/usr/bin/linuxtoys b/appimagebuild/LinuxToys.AppDir/usr/bin/linuxtoys
--- a/appimagebuild/LinuxToys.AppDir/usr/bin/linuxtoys
+++ b/appimagebuild/LinuxToys.AppDir/usr/bin/linuxtoys
@@ -1,16 +1,23 @@
 #!/bin/bash
 # functions
+fatal() {
+    zenity --error --title "Fatal Error" --text "$1" --height=300 --width=300
+    exit 1
+}
+
+# sudo request
+sudo_rq () {
+    zenity --password | sudo -Sv || fatal "Wrong password. Do you have sudo?"
+}
 
 # updater
-current_ltver="3.2"
+current_ltver="4.3"
 ver_upd () {
     local ver
     ver=$(curl -s https://raw.githubusercontent.com/psygreg/linuxtoys/refs/heads/main/src/ver)
     if [[ "$ver" != "$current_ltver" ]]; then
-        if whiptail --title "$msg001" --yesno "$msg002" 8 78; then
-            local title="$msg001"
-            local msg="$msg157"
-            _msgbox_
+        if zenity --question --title "$msg001" --text "$msg002" --width 300 --height 300; then
+            zeninf "$msg157"
             xdg-open https://github.com/psygreg/linuxtoys/releases/latest         
         fi
     fi
@@ -20,53 +27,59 @@ ver_upd () {
 # check internet connection
 # ping google
 . /etc/os-release
-wget -q -O - "https://raw.githubusercontent.com/psygreg/linuxtoys/refs/heads/main/README.md" > /dev/null || { whiptail --title "Disconnected" --msgbox "LinuxToys requires an internet connection to proceed." 8 78; exit 1; }
+wget -q -O - "https://raw.githubusercontent.com/psygreg/linuxtoys/refs/heads/main/README.md" > /dev/null || fatal "LinuxToys requires an internet connection to proceed."
 # call linuxtoys turbobash lib
-source <(curl -s https://raw.githubusercontent.com/psygreg/linuxtoys/refs/heads/main/src/linuxtoys.lib)
+sleep 1
+source linuxtoys.lib
 # logger
 logfile="$HOME/.local/linuxtoys-log.txt"
 _log_
 # language and upd checks
 _lang_
-source <(curl -s https://raw.githubusercontent.com/psygreg/linuxtoys/refs/heads/main/src/lang/${langfile})
+source ${langfile}
+sleep 1
 ver_upd
+sudo_rq
 
 # main menu
-while :; do
+while true; do
 
-    CHOICE=$(whiptail --title "LinuxToys" --menu "LinuxToys ${current_ltver}" 25 78 16 \
-        "0" "$msg120" \
-        "1" "$msg121" \
-        "2" "$msg122" \
-        "3" "${msg123}*" \
-        "4" "${msg143}*" \
-        "5" "$msg227" \
-        "6" "$msg199" \
-        "" "" \
-        "" "" \
-        "8" "$msg124" \
-        "9" "GitHub" \
-        "10" "$msg059" 3>&1 1>&2 2>&3)
+    CHOICE=$(zenity --list --title "LinuxToys" \
+        --column="$msg274"  \
+        "$msg120" \
+        "$msg121" \
+        "$msg122" \
+        "${msg123}" \
+        "${msg143}" \
+        "$msg227" \
+        "$msg199" \
+        "$msg279" \
+        "" \
+        "$msg124" \
+        "Wiki" \
+        "${msg275}" \
+        "$msg059" \
+        --height=530 --width=360)
         #"7" "UniWine" \ -- disabled option
 
-    exitstatus=$?
-    if [ $exitstatus != 0 ]; then
-        # Exit the script if the user presses Esc
-        find "$HOME" -maxdepth 1 -type f -name '*supermenu.sh' -exec rm -f {} + && break
-    fi
+    if [ $? -ne 0 ]; then
+        find "$HOME" -maxdepth 1 -type f -name '*.sh' -exec rm -f {} + && break
+   	fi
 
     case $CHOICE in
-    0) supmenu="usupermenu" && _invoke_ ;;
-    1) supmenu="osupermenu" && _invoke_ ;;
-    2) supmenu="gsupermenu" && _invoke_ ;;
-    3) supmenu="esupermenu" && _invoke_ ;;
-    4) supmenu="dsupermenu" && _invoke_ ;;
-    5) subscript="pdefaults" && _invoke_ ;;
-    6) supmenu="csupermenu" && _invoke_ ;;
+    "$msg120") supmenu="usupermenu" && _invoke_ ;;
+    "$msg121") supmenu="osupermenu" && _invoke_ ;;
+    "$msg122") supmenu="gsupermenu" && _invoke_ ;;
+    "${msg123}") supmenu="esupermenu" && _invoke_ ;;
+    "${msg143}") supmenu="dsupermenu" && _invoke_ ;;
+    "$msg227") subscript="pdefaults" && _invoke_ ;;
+    "$msg199") supmenu="csupermenu" && _invoke_ ;;
+    "$msg279") subscript="psypicks" && _invoke_ ;;
     # 7) subscript="uniwine" && _invoke_ ;; -- disabled option
-    8) whiptail --title "LinuxToys v${current_ltver}" --msgbox "$msg125" 8 78 ;;
-    9) xdg-open https://github.com/psygreg/linuxtoys ;;
-    10 | q) break ;;
+    "$msg124") zeninf "$msg125";;
+    "Wiki") xdg-open https://github.com/psygreg/linuxtoys/wiki ;;
+    "${msg275}") xdg-open https://ko-fi.com/psygreg ;;
+    "$msg059") break ;;
     *) echo "Invalid Option" ;;
     esac
 done
